import type { Surah } from './types';

export const ALL_SURAHS: Surah[] = [
  { id: 1, nameArabic: 'ٱلْفَاتِحَة', nameRoman: 'Al-Fatihah', nameMalay: 'Pembukaan', verseCount: 7 },
  { id: 2, nameArabic: 'ٱلْبَقَرَة', nameRoman: 'Al-Baqarah', nameMalay: 'Sapi Betina', verseCount: 286 },
  { id: 3, nameArabic: 'آلِ عِمْرَان', nameRoman: 'Ali \'Imran', nameMalay: 'Keluarga Imran', verseCount: 200 },
  { id: 4, nameArabic: 'ٱلنِّسَاء', nameRoman: 'An-Nisa\'', nameMalay: 'Wanita', verseCount: 176 },
  { id: 5, nameArabic: 'ٱلْمَائِدَة', nameRoman: 'Al-Ma\'idah', nameMalay: 'Jamuan (Hidangan Makanan)', verseCount: 120 },
  { id: 6, nameArabic: 'ٱلْأَنْعَام', nameRoman: 'Al-An\'am', nameMalay: 'Binatang Ternak', verseCount: 165 },
  { id: 7, nameArabic: 'ٱلْأَعْرَاف', nameRoman: 'Al-A\'raf', nameMalay: 'Tempat yang Tertinggi', verseCount: 206 },
  { id: 8, nameArabic: 'ٱلْأَنْفَال', nameRoman: 'Al-Anfal', nameMalay: 'Harta Rampasan Perang', verseCount: 75 },
  { id: 9, nameArabic: 'ٱلتَّوْبَة', nameRoman: 'At-Tawbah', nameMalay: 'Pengampunan', verseCount: 129 },
  { id: 10, nameArabic: 'يُونُس', nameRoman: 'Yunus', nameMalay: 'Nabi Yunus', verseCount: 109 },
  { id: 11, nameArabic: 'هُود', nameRoman: 'Hud', nameMalay: 'Nabi Hud', verseCount: 123 },
  { id: 12, nameArabic: 'يُوسُف', nameRoman: 'Yusuf', nameMalay: 'Nabi Yusuf', verseCount: 111 },
  { id: 13, nameArabic: 'ٱلرَّعْد', nameRoman: 'Ar-Ra\'d', nameMalay: 'Guruh (Petir)', verseCount: 43 },
  { id: 14, nameArabic: 'إِبْرَاهِيم', nameRoman: 'Ibrahim', nameMalay: 'Nabi Ibrahim', verseCount: 52 },
  { id: 15, nameArabic: 'ٱلْحِجْر', nameRoman: 'Al-Hijr', nameMalay: 'Gunung Al-Hijr', verseCount: 99 },
  { id: 16, nameArabic: 'ٱلنَّحْل', nameRoman: 'An-Nahl', nameMalay: 'Lebah', verseCount: 128 },
  { id: 17, nameArabic: 'ٱلْإِسْرَاء', nameRoman: 'Al-Isra\'', nameMalay: 'Perjalanan Malam', verseCount: 111 },
  { id: 18, nameArabic: 'ٱلْكَهْف', nameRoman: 'Al-Kahf', nameMalay: 'Penghuni-penghuni Gua', verseCount: 110 },
  { id: 19, nameArabic: 'مَرْيَم', nameRoman: 'Maryam', nameMalay: 'Siti Maryam', verseCount: 98 },
  { id: 20, nameArabic: 'طه', nameRoman: 'Taha', nameMalay: 'Ta Ha', verseCount: 135 },
  { id: 21, nameArabic: 'ٱلْأَنْبِيَاء', nameRoman: 'Al-Anbiya\'', nameMalay: 'Nabi-Nabi', verseCount: 112 },
  { id: 22, nameArabic: 'ٱلْحَجّ', nameRoman: 'Al-Hajj', nameMalay: 'Haji', verseCount: 78 },
  { id: 23, nameArabic: 'ٱلْمُؤْمِنُون', nameRoman: 'Al-Mu\'minun', nameMalay: 'Orang-orang mukmin', verseCount: 118 },
  { id: 24, nameArabic: 'ٱلنُّور', nameRoman: 'An-Nur', nameMalay: 'Cahaya', verseCount: 64 },
  { id: 25, nameArabic: 'ٱلْفُرْقَان', nameRoman: 'Al-Furqan', nameMalay: 'Pembeda', verseCount: 77 },
  { id: 26, nameArabic: 'ٱلشُّعَرَاء', nameRoman: 'Asy-Syu\'ara\'', nameMalay: 'Penyair', verseCount: 227 },
  { id: 27, nameArabic: 'ٱلنَّمْل', nameRoman: 'An-Naml', nameMalay: 'Semut', verseCount: 93 },
  { id: 28, nameArabic: 'ٱلْقَصَص', nameRoman: 'Al-Qasas', nameMalay: 'Cerita', verseCount: 88 },
  { id: 29, nameArabic: 'ٱلْعَنْكَبُوت', nameRoman: 'Al-\'Ankabut', nameMalay: 'Laba-laba', verseCount: 69 },
  { id: 30, nameArabic: 'ٱلرُّوم', nameRoman: 'Ar-Rum', nameMalay: 'Bangsa Romawi', verseCount: 60 },
  { id: 31, nameArabic: 'لُقْمَان', nameRoman: 'Luqman', nameMalay: 'Luqman', verseCount: 34 },
  { id: 32, nameArabic: 'ٱلسَّجْدَة', nameRoman: 'As-Sajdah', nameMalay: 'Sujud', verseCount: 30 },
  { id: 33, nameArabic: 'ٱلْأَحْزَاب', nameRoman: 'Al-Ahzab', nameMalay: 'Golongan-golongan yang Bersekutu', verseCount: 73 },
  { id: 34, nameArabic: 'سَبَأ', nameRoman: 'Saba\'', nameMalay: 'Kaum Saba\'', verseCount: 54 },
  { id: 35, nameArabic: 'فَاطِر', nameRoman: 'Fatir', nameMalay: 'Pencipta', verseCount: 45 },
  { id: 36, nameArabic: 'يس', nameRoman: 'Ya-Sin', nameMalay: 'Ya Sin', verseCount: 83 },
  { id: 37, nameArabic: 'ٱلصَّافَّات', nameRoman: 'As-Saffat', nameMalay: 'Barisan-barisan', verseCount: 182 },
  { id: 38, nameArabic: 'ص', nameRoman: 'Sad', nameMalay: 'Sad', verseCount: 88 },
  { id: 39, nameArabic: 'ٱلزُّمَر', nameRoman: 'Az-Zumar', nameMalay: 'Rombongan-rombongan', verseCount: 75 },
  { id: 40, nameArabic: 'غَافِر', nameRoman: 'Ghafir', nameMalay: 'Yang Mengampuni', verseCount: 85 },
  { id: 41, nameArabic: 'فُصِّلَت', nameRoman: 'Fussilat', nameMalay: 'Yang Dijelaskan', verseCount: 54 },
  { id: 42, nameArabic: 'ٱلشُّورَىٰ', nameRoman: 'Asy-Syura', nameMalay: 'Musyawarah', verseCount: 53 },
  { id: 43, nameArabic: 'ٱلزُّخْرُف', nameRoman: 'Az-Zukhruf', nameMalay: 'Perhiasan', verseCount: 89 },
  { id: 44, nameArabic: 'ٱلدُّخَان', nameRoman: 'Ad-Dukhan', nameMalay: 'Kabut', verseCount: 59 },
  { id: 45, nameArabic: 'ٱلْجَاثِيَة', nameRoman: 'Al-Jasiyah', nameMalay: 'Yang Bertekuk Lutut', verseCount: 37 },
  { id: 46, nameArabic: 'ٱلْأَحْقَاف', nameRoman: 'Al-Ahqaf', nameMalay: 'Bukit-bukit Pasir', verseCount: 35 },
  { id: 47, nameArabic: 'مُحَمَّد', nameRoman: 'Muhammad', nameMalay: 'Nabi Muhammad', verseCount: 38 },
  { id: 48, nameArabic: 'ٱلْفَتْح', nameRoman: 'Al-Fath', nameMalay: 'Kemenangan', verseCount: 29 },
  { id: 49, nameArabic: 'ٱلْحُجُرَات', nameRoman: 'Al-Hujurat', nameMalay: 'Kamar-kamar', verseCount: 18 },
  { id: 50, nameArabic: 'ق', nameRoman: 'Qaf', nameMalay: 'Qaf', verseCount: 45 },
  { id: 51, nameArabic: 'ٱلذَّارِيَات', nameRoman: 'Az-Zariyat', nameMalay: 'Angin yang Menerbangkan', verseCount: 60 },
  { id: 52, nameArabic: 'ٱلطُّور', nameRoman: 'At-Tur', nameMalay: 'Bukit', verseCount: 49 },
  { id: 53, nameArabic: 'ٱلنَّجْم', nameRoman: 'An-Najm', nameMalay: 'Bintang', verseCount: 62 },
  { id: 54, nameArabic: 'ٱلْقَمَر', nameRoman: 'Al-Qamar', nameMalay: 'Bulan', verseCount: 55 },
  { id: 55, nameArabic: 'ٱلرَّحْمَٰن', nameRoman: 'Ar-Rahman', nameMalay: 'Yang Maha Pemurah', verseCount: 78 },
  { id: 56, nameArabic: 'ٱلْوَاقِعَة', nameRoman: 'Al-Waqi\'ah', nameMalay: 'Hari Kiamat', verseCount: 96 },
  { id: 57, nameArabic: 'ٱلْحَدِيد', nameRoman: 'Al-Hadid', nameMalay: 'Besi', verseCount: 29 },
  { id: 58, nameArabic: 'ٱلْمُجَادِلَة', nameRoman: 'Al-Mujadilah', nameMalay: 'Wanita yang Mengajukan Gugatan', verseCount: 22 },
  { id: 59, nameArabic: 'ٱلْحَشْر', nameRoman: 'Al-Hasyr', nameMalay: 'Pengusiran', verseCount: 24 },
  { id: 60, nameArabic: 'ٱلْمُمْتَحَنَة', nameRoman: 'Al-Mumtahanah', nameMalay: 'Wanita yang Diuji', verseCount: 13 },
  { id: 61, nameArabic: 'ٱلصَّفّ', nameRoman: 'As-Saff', nameMalay: 'Satu Barisan', verseCount: 14 },
  { id: 62, nameArabic: 'ٱلْجُمُعَة', nameRoman: 'Al-Jumu\'ah', nameMalay: 'Hari Jum\'at', verseCount: 11 },
  { id: 63, nameArabic: 'ٱلْمُنَافِقُون', nameRoman: 'Al-Munafiqun', nameMalay: 'Orang-orang yang Munafik', verseCount: 11 },
  { id: 64, nameArabic: 'ٱلتَّغَابُن', nameRoman: 'At-Tagabun', nameMalay: 'Hari Dinampakkan Kesalahan-kesalahan', verseCount: 18 },
  { id: 65, nameArabic: 'ٱلطَّلَاق', nameRoman: 'At-Talaq', nameMalay: 'Talak', verseCount: 12 },
  { id: 66, nameArabic: 'ٱلتَّحْرِيم', nameRoman: 'At-Tahrim', nameMalay: 'Mengharamkan', verseCount: 12 },
  { id: 67, nameArabic: 'ٱلْمُلْك', nameRoman: 'Al-Mulk', nameMalay: 'Kerajaan', verseCount: 30 },
  { id: 68, nameArabic: 'ٱلْقَلَم', nameRoman: 'Al-Qalam', nameMalay: 'Pena', verseCount: 52 },
  { id: 69, nameArabic: 'ٱلْحَاقَّة', nameRoman: 'Al-Haqqah', nameMalay: 'Hari Kiamat', verseCount: 52 },
  { id: 70, nameArabic: 'ٱلْمَعَارِج', nameRoman: 'Al-Ma\'arij', nameMalay: 'Tempat Naik', verseCount: 44 },
  { id: 71, nameArabic: 'نُوح', nameRoman: 'Nuh', nameMalay: 'Nabi Nuh', verseCount: 28 },
  { id: 72, nameArabic: 'ٱلْجِنّ', nameRoman: 'Al-Jinn', nameMalay: 'Jin', verseCount: 28 },
  { id: 73, nameArabic: 'ٱلْمُزَّمِّل', nameRoman: 'Al-Muzzammil', nameMalay: 'Orang yang Berselimut', verseCount: 20 },
  { id: 74, nameArabic: 'ٱلْمُدَّثِّر', nameRoman: 'Al-Muddassir', nameMalay: 'Orang yang Berkemul', verseCount: 56 },
  { id: 75, nameArabic: 'ٱلْقِيَامَة', nameRoman: 'Al-Qiyamah', nameMalay: 'Hari Kiamat', verseCount: 40 },
  { id: 76, nameArabic: 'ٱلْإِنْسَان', nameRoman: 'Al-Insan', nameMalay: 'Manusia', verseCount: 31 },
  { id: 77, nameArabic: 'ٱلْمُرْسَلَات', nameRoman: 'Al-Mursalat', nameMalay: 'Malaikat-Malaikat yang Diutus', verseCount: 50 },
  { id: 78, nameArabic: 'ٱلنَّبَإ', nameRoman: 'An-Naba\'', nameMalay: 'Berita Besar', verseCount: 40 },
  { id: 79, nameArabic: 'ٱلنَّازِعَات', nameRoman: 'An-Nazi\'at', nameMalay: 'Malaikat-Malaikat yang Mencabut', verseCount: 46 },
  { id: 80, nameArabic: 'عَبَسَ', nameRoman: 'Abasa', nameMalay: 'Ia Bermuka Masam', verseCount: 42 },
  { id: 81, nameArabic: 'ٱلتَّكْوِير', nameRoman: 'At-Takwir', nameMalay: 'Menggulung', verseCount: 29 },
  { id: 82, nameArabic: 'ٱلْإِنْفِطَار', nameRoman: 'Al-Infitar', nameMalay: 'Terbelah', verseCount: 19 },
  { id: 83, nameArabic: 'ٱلْمُطَفِّفِين', nameRoman: 'Al-Mutaffifin', nameMalay: 'Orang-orang yang Curang', verseCount: 36 },
  { id: 84, nameArabic: 'ٱلْإِنْشِقَاق', nameRoman: 'Al-Insyiqaq', nameMalay: 'Terbelah', verseCount: 25 },
  { id: 85, nameArabic: 'ٱلْبُرُوج', nameRoman: 'Al-Buruj', nameMalay: 'Gugusan Bintang', verseCount: 22 },
  { id: 86, nameArabic: 'ٱلطَّارِق', nameRoman: 'At-Tariq', nameMalay: 'Yang Datang di Malam Hari', verseCount: 17 },
  { id: 87, nameArabic: 'ٱلْأَعْلَىٰ', nameRoman: 'Al-A\'la', nameMalay: 'Yang Paling Tinggi', verseCount: 19 },
  { id: 88, nameArabic: 'ٱلْغَاشِيَة', nameRoman: 'Al-Gasyiyah', nameMalay: 'Hari Pembalasan', verseCount: 26 },
  { id: 89, nameArabic: 'ٱلْفَجْر', nameRoman: 'Al-Fajr', nameMalay: 'Fajar', verseCount: 30 },
  { id: 90, nameArabic: 'ٱلْبَلَد', nameRoman: 'Al-Balad', nameMalay: 'Negeri', verseCount: 20 },
  { id: 91, nameArabic: 'ٱلشَّمْس', nameRoman: 'Asy-Syams', nameMalay: 'Matahari', verseCount: 15 },
  { id: 92, nameArabic: 'ٱللَّيْل', nameRoman: 'Al-Lail', nameMalay: 'Malam', verseCount: 21 },
  { id: 93, nameArabic: 'ٱلضُّحَىٰ', nameRoman: 'Ad-Duha', nameMalay: 'Waktu Dhuha', verseCount: 11 },
  { id: 94, nameArabic: 'ٱلشَّرْح', nameRoman: 'Asy-Syarh', nameMalay: 'Melapangkan', verseCount: 8 },
  { id: 95, nameArabic: 'ٱلتِّين', nameRoman: 'At-Tin', nameMalay: 'Buah Tin', verseCount: 8 },
  { id: 96, nameArabic: 'ٱلْعَلَق', nameRoman: 'Al-\'Alaq', nameMalay: 'Segumpal Darah', verseCount: 19 },
  { id: 97, nameArabic: 'ٱلْقَدْر', nameRoman: 'Al-Qadr', nameMalay: 'Kemuliaan', verseCount: 5 },
  { id: 98, nameArabic: 'ٱلْبَيِّنَة', nameRoman: 'Al-Bayyinah', nameMalay: 'Pembuktian', verseCount: 8 },
  { id: 99, nameArabic: 'ٱلزَّلْزَلَة', nameRoman: 'Az-Zalzalah', nameMalay: 'Kegoncangan', verseCount: 8 },
  { id: 100, nameArabic: 'ٱلْعَادِيَات', nameRoman: 'Al-\'Adiyat', nameMalay: 'Berlari Kencang', verseCount: 11 },
  { id: 101, nameArabic: 'ٱلْقَارِعَة', nameRoman: 'Al-Qari\'ah', nameMalay: 'Hari Kiamat', verseCount: 11 },
  { id: 102, nameArabic: 'ٱلتَّكَاثُر', nameRoman: 'At-Takasur', nameMalay: 'Bermegah-megahan', verseCount: 8 },
  { id: 103, nameArabic: 'ٱلْعَصْر', nameRoman: 'Al-\'Asr', nameMalay: 'Masa', verseCount: 3 },
  { id: 104, nameArabic: 'ٱلْهُمَزَة', nameRoman: 'Al-Humazah', nameMalay: 'Pengumpat', verseCount: 9 },
  { id: 105, nameArabic: 'ٱلْفِيل', nameRoman: 'Al-Fil', nameMalay: 'Gajah', verseCount: 5 },
  { id: 106, nameArabic: 'قُرَيْش', nameRoman: 'Quraisy', nameMalay: 'Suku Quraisy', verseCount: 4 },
  { id: 107, nameArabic: 'ٱلْمَاعُون', nameRoman: 'Al-Ma\'un', nameMalay: 'Barang-barang yang Berguna', verseCount: 7 },
  { id: 108, nameArabic: 'ٱلْكَوْثَر', nameRoman: 'Al-Kausar', nameMalay: 'Nikmat yang Berlimpah', verseCount: 3 },
  { id: 109, nameArabic: 'ٱلْكَافِرُون', nameRoman: 'Al-Kafirun', nameMalay: 'Orang-orang Kafir', verseCount: 6 },
  { id: 110, nameArabic: 'ٱلنَّصْر', nameRoman: 'An-Nasr', nameMalay: 'Pertolongan', verseCount: 3 },
  { id: 111, nameArabic: 'ٱلْمَسَد', nameRoman: 'Al-Masad', nameMalay: 'Gejolak Api', verseCount: 5 },
  { id: 112, nameArabic: 'ٱلْإِخْلَاص', nameRoman: 'Al-Ikhlas', nameMalay: 'Ikhlas', verseCount: 4 },
  { id: 113, nameArabic: 'ٱلْفَلَق', nameRoman: 'Al-Falaq', nameMalay: 'Waktu Subuh', verseCount: 5 },
  { id: 114, nameArabic: 'ٱلنَّاس', nameRoman: 'An-Nas', nameMalay: 'Manusia', verseCount: 6 }
];

export const QURANIC_THEMES = [
  "Sabar dalam Ujian",
  "Syukur atas Nikmat",
  "Kisah Para Nabi",
  "Keagungan Ciptaan Allah",
  "Hari Kiamat",
  "Keadilan dan Keseimbangan",
  "Pentingnya Keluarga",
  "Bahaya Sifat Sombong"
];
